CREATE TABLE IF NOT EXISTS `countries` (
  `isocode` varchar(2) NOT NULL,
  `longcode` varchar(3) NOT NULL,
  `description` varchar(50) NOT NULL,
  PRIMARY KEY (`isocode`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `audit` (
  `item` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO countries(isocode,longcode,description) VALUES ('AF','AFG','Afghanistan');
INSERT INTO countries(isocode,longcode,description) VALUES ('AX','ALA','Aland Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('AL','ALB','Albania');
INSERT INTO countries(isocode,longcode,description) VALUES ('DZ','DZA','Algeria');
INSERT INTO countries(isocode,longcode,description) VALUES ('AS','ASM','American Samoa');
INSERT INTO countries(isocode,longcode,description) VALUES ('AD','AND','Andorra');
INSERT INTO countries(isocode,longcode,description) VALUES ('AO','AGO','Angola');
INSERT INTO countries(isocode,longcode,description) VALUES ('AI','AIA','Anguilla');
INSERT INTO countries(isocode,longcode,description) VALUES ('AQ','ATA','Antarctica');
INSERT INTO countries(isocode,longcode,description) VALUES ('AG','ATG','Antigua and Barbuda');
INSERT INTO countries(isocode,longcode,description) VALUES ('AR','ARG','Argentina');
INSERT INTO countries(isocode,longcode,description) VALUES ('AM','ARM','Armenia');
INSERT INTO countries(isocode,longcode,description) VALUES ('AW','ABW','Aruba');
INSERT INTO countries(isocode,longcode,description) VALUES ('AU','AUS','Australia');
INSERT INTO countries(isocode,longcode,description) VALUES ('AT','AUT','Austria');
INSERT INTO countries(isocode,longcode,description) VALUES ('AZ','AZE','Azerbaijan');
INSERT INTO countries(isocode,longcode,description) VALUES ('BS','BHS','Bahamas');
INSERT INTO countries(isocode,longcode,description) VALUES ('BH','BHR','Bahrain');
INSERT INTO countries(isocode,longcode,description) VALUES ('BD','BGD','Bangladesh');
INSERT INTO countries(isocode,longcode,description) VALUES ('BB','BRB','Barbados');
INSERT INTO countries(isocode,longcode,description) VALUES ('BY','BLR','Belarus');
INSERT INTO countries(isocode,longcode,description) VALUES ('BE','BEL','Belgium');
INSERT INTO countries(isocode,longcode,description) VALUES ('BZ','BLZ','Belize');
INSERT INTO countries(isocode,longcode,description) VALUES ('BJ','BEN','Benin');
INSERT INTO countries(isocode,longcode,description) VALUES ('BM','BMU','Bermuda');
INSERT INTO countries(isocode,longcode,description) VALUES ('BT','BTN','Bhutan');
INSERT INTO countries(isocode,longcode,description) VALUES ('BO','BOL','Bolivia');
INSERT INTO countries(isocode,longcode,description) VALUES ('BA','BIH','Bosnia and Herzegovina');
INSERT INTO countries(isocode,longcode,description) VALUES ('BW','BWA','Botswana');
INSERT INTO countries(isocode,longcode,description) VALUES ('BV','BVT','Bouvet Island');
INSERT INTO countries(isocode,longcode,description) VALUES ('BR','BRA','Brazil');
INSERT INTO countries(isocode,longcode,description) VALUES ('VG','VGB','British Virgin Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('IO','IOT','British Indian Ocean Territory');
INSERT INTO countries(isocode,longcode,description) VALUES ('BN','BRN','Brunei Darussalam');
INSERT INTO countries(isocode,longcode,description) VALUES ('BG','BGR','Bulgaria');
INSERT INTO countries(isocode,longcode,description) VALUES ('BF','BFA','Burkina Faso');
INSERT INTO countries(isocode,longcode,description) VALUES ('BI','BDI','Burundi');
INSERT INTO countries(isocode,longcode,description) VALUES ('KH','KHM','Cambodia');
INSERT INTO countries(isocode,longcode,description) VALUES ('CM','CMR','Cameroon');
INSERT INTO countries(isocode,longcode,description) VALUES ('CA','CAN','Canada');
INSERT INTO countries(isocode,longcode,description) VALUES ('CV','CPV','Cape Verde');
INSERT INTO countries(isocode,longcode,description) VALUES ('KY','CYM','Cayman Islands ');
INSERT INTO countries(isocode,longcode,description) VALUES ('CF','CAF','Central African Republic');
INSERT INTO countries(isocode,longcode,description) VALUES ('TD','TCD','Chad');
INSERT INTO countries(isocode,longcode,description) VALUES ('CL','CHL','Chile');
INSERT INTO countries(isocode,longcode,description) VALUES ('CN','CHN','China');
INSERT INTO countries(isocode,longcode,description) VALUES ('HK','HKG','Hong Kong, Special Administrative Region of China');
INSERT INTO countries(isocode,longcode,description) VALUES ('MO','MAC','Macao, Special Administrative Region of China');
INSERT INTO countries(isocode,longcode,description) VALUES ('CX','CXR','Christmas Island');
INSERT INTO countries(isocode,longcode,description) VALUES ('CC','CCK','Cocos (Keeling) Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('CO','COL','Colombia');
INSERT INTO countries(isocode,longcode,description) VALUES ('KM','COM','Comoros');
INSERT INTO countries(isocode,longcode,description) VALUES ('CG','COG','Congo (Brazzaville)');
INSERT INTO countries(isocode,longcode,description) VALUES ('CD','COD','Congo, Democratic Republic of the');
INSERT INTO countries(isocode,longcode,description) VALUES ('CK','COK','Cook Islands ');
INSERT INTO countries(isocode,longcode,description) VALUES ('CR','CRI','Costa Rica');
INSERT INTO countries(isocode,longcode,description) VALUES ('CI','CIV','Côte d''Ivoire');
INSERT INTO countries(isocode,longcode,description) VALUES ('HR','HRV','Croatia');
INSERT INTO countries(isocode,longcode,description) VALUES ('CU','CUB','Cuba');
INSERT INTO countries(isocode,longcode,description) VALUES ('CY','CYP','Cyprus');
INSERT INTO countries(isocode,longcode,description) VALUES ('CZ','CZE','Czech Republic');
INSERT INTO countries(isocode,longcode,description) VALUES ('DK','DNK','Denmark');
INSERT INTO countries(isocode,longcode,description) VALUES ('DJ','DJI','Djibouti');
INSERT INTO countries(isocode,longcode,description) VALUES ('DM','DMA','Dominica');
INSERT INTO countries(isocode,longcode,description) VALUES ('DO','DOM','Dominican Republic');
INSERT INTO countries(isocode,longcode,description) VALUES ('EC','ECU','Ecuador');
INSERT INTO countries(isocode,longcode,description) VALUES ('EG','EGY','Egypt');
INSERT INTO countries(isocode,longcode,description) VALUES ('SV','SLV','El Salvador');
INSERT INTO countries(isocode,longcode,description) VALUES ('GQ','GNQ','Equatorial Guinea');
INSERT INTO countries(isocode,longcode,description) VALUES ('ER','ERI','Eritrea');
INSERT INTO countries(isocode,longcode,description) VALUES ('EE','EST','Estonia');
INSERT INTO countries(isocode,longcode,description) VALUES ('ET','ETH','Ethiopia');
INSERT INTO countries(isocode,longcode,description) VALUES ('FK','FLK','Falkland Islands (Malvinas) ');
INSERT INTO countries(isocode,longcode,description) VALUES ('FO','FRO','Faroe Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('FJ','FJI','Fiji');
INSERT INTO countries(isocode,longcode,description) VALUES ('FI','FIN','Finland');
INSERT INTO countries(isocode,longcode,description) VALUES ('FR','FRA','France');
INSERT INTO countries(isocode,longcode,description) VALUES ('GF','GUF','French Guiana');
INSERT INTO countries(isocode,longcode,description) VALUES ('PF','PYF','French Polynesia');
INSERT INTO countries(isocode,longcode,description) VALUES ('TF','ATF','French Southern Territories');
INSERT INTO countries(isocode,longcode,description) VALUES ('GA','GAB','Gabon');
INSERT INTO countries(isocode,longcode,description) VALUES ('GM','GMB','Gambia');
INSERT INTO countries(isocode,longcode,description) VALUES ('GE','GEO','Georgia');
INSERT INTO countries(isocode,longcode,description) VALUES ('DE','DEU','Germany');
INSERT INTO countries(isocode,longcode,description) VALUES ('GH','GHA','Ghana');
INSERT INTO countries(isocode,longcode,description) VALUES ('GI','GIB','Gibraltar ');
INSERT INTO countries(isocode,longcode,description) VALUES ('GR','GRC','Greece');
INSERT INTO countries(isocode,longcode,description) VALUES ('GL','GRL','Greenland');
INSERT INTO countries(isocode,longcode,description) VALUES ('GD','GRD','Grenada');
INSERT INTO countries(isocode,longcode,description) VALUES ('GP','GLP','Guadeloupe');
INSERT INTO countries(isocode,longcode,description) VALUES ('GU','GUM','Guam');
INSERT INTO countries(isocode,longcode,description) VALUES ('GT','GTM','Guatemala');
INSERT INTO countries(isocode,longcode,description) VALUES ('GG','GGY','Guernsey');
INSERT INTO countries(isocode,longcode,description) VALUES ('GN','GIN','Guinea');
INSERT INTO countries(isocode,longcode,description) VALUES ('GW','GNB','Guinea-Bissau');
INSERT INTO countries(isocode,longcode,description) VALUES ('GY','GUY','Guyana');
INSERT INTO countries(isocode,longcode,description) VALUES ('HT','HTI','Haiti');
INSERT INTO countries(isocode,longcode,description) VALUES ('HM','HMD','Heard Island and Mcdonald Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('VA','VAT','Holy See (Vatican City State)');
INSERT INTO countries(isocode,longcode,description) VALUES ('HN','HND','Honduras');
INSERT INTO countries(isocode,longcode,description) VALUES ('HU','HUN','Hungary');
INSERT INTO countries(isocode,longcode,description) VALUES ('IS','ISL','Iceland');
INSERT INTO countries(isocode,longcode,description) VALUES ('IN','IND','India');
INSERT INTO countries(isocode,longcode,description) VALUES ('ID','IDN','Indonesia');
INSERT INTO countries(isocode,longcode,description) VALUES ('IR','IRN','Iran, Islamic Republic of');
INSERT INTO countries(isocode,longcode,description) VALUES ('IQ','IRQ','Iraq');
INSERT INTO countries(isocode,longcode,description) VALUES ('IE','IRL','Ireland');
INSERT INTO countries(isocode,longcode,description) VALUES ('IM','IMN','Isle of Man ');
INSERT INTO countries(isocode,longcode,description) VALUES ('IL','ISR','Israel');
INSERT INTO countries(isocode,longcode,description) VALUES ('IT','ITA','Italy');
INSERT INTO countries(isocode,longcode,description) VALUES ('JM','JAM','Jamaica');
INSERT INTO countries(isocode,longcode,description) VALUES ('JP','JPN','Japan');
INSERT INTO countries(isocode,longcode,description) VALUES ('JE','JEY','Jersey');
INSERT INTO countries(isocode,longcode,description) VALUES ('JO','JOR','Jordan');
INSERT INTO countries(isocode,longcode,description) VALUES ('KZ','KAZ','Kazakhstan');
INSERT INTO countries(isocode,longcode,description) VALUES ('KE','KEN','Kenya');
INSERT INTO countries(isocode,longcode,description) VALUES ('KI','KIR','Kiribati');
INSERT INTO countries(isocode,longcode,description) VALUES ('KP','PRK','Korea, Democratic People''s Republic of');
INSERT INTO countries(isocode,longcode,description) VALUES ('KR','KOR','Korea, Republic of');
INSERT INTO countries(isocode,longcode,description) VALUES ('KW','KWT','Kuwait');
INSERT INTO countries(isocode,longcode,description) VALUES ('KG','KGZ','Kyrgyzstan');
INSERT INTO countries(isocode,longcode,description) VALUES ('LA','LAO','Lao PDR');
INSERT INTO countries(isocode,longcode,description) VALUES ('LV','LVA','Latvia');
INSERT INTO countries(isocode,longcode,description) VALUES ('LB','LBN','Lebanon');
INSERT INTO countries(isocode,longcode,description) VALUES ('LS','LSO','Lesotho');
INSERT INTO countries(isocode,longcode,description) VALUES ('LR','LBR','Liberia');
INSERT INTO countries(isocode,longcode,description) VALUES ('LY','LBY','Libya');
INSERT INTO countries(isocode,longcode,description) VALUES ('LI','LIE','Liechtenstein');
INSERT INTO countries(isocode,longcode,description) VALUES ('LT','LTU','Lithuania');
INSERT INTO countries(isocode,longcode,description) VALUES ('LU','LUX','Luxembourg');
INSERT INTO countries(isocode,longcode,description) VALUES ('MK','MKD','Macedonia, Republic of');
INSERT INTO countries(isocode,longcode,description) VALUES ('MG','MDG','Madagascar');
INSERT INTO countries(isocode,longcode,description) VALUES ('MW','MWI','Malawi');
INSERT INTO countries(isocode,longcode,description) VALUES ('MY','MYS','Malaysia');
INSERT INTO countries(isocode,longcode,description) VALUES ('MV','MDV','Maldives');
INSERT INTO countries(isocode,longcode,description) VALUES ('ML','MLI','Mali');
INSERT INTO countries(isocode,longcode,description) VALUES ('MT','MLT','Malta');
INSERT INTO countries(isocode,longcode,description) VALUES ('MH','MHL','Marshall Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('MQ','MTQ','Martinique');
INSERT INTO countries(isocode,longcode,description) VALUES ('MR','MRT','Mauritania');
INSERT INTO countries(isocode,longcode,description) VALUES ('MU','MUS','Mauritius');
INSERT INTO countries(isocode,longcode,description) VALUES ('YT','MYT','Mayotte');
INSERT INTO countries(isocode,longcode,description) VALUES ('MX','MEX','Mexico');
INSERT INTO countries(isocode,longcode,description) VALUES ('FM','FSM','Micronesia, Federated States of');
INSERT INTO countries(isocode,longcode,description) VALUES ('MD','MDA','Moldova');
INSERT INTO countries(isocode,longcode,description) VALUES ('MC','MCO','Monaco');
INSERT INTO countries(isocode,longcode,description) VALUES ('MN','MNG','Mongolia');
INSERT INTO countries(isocode,longcode,description) VALUES ('ME','MNE','Montenegro');
INSERT INTO countries(isocode,longcode,description) VALUES ('MS','MSR','Montserrat');
INSERT INTO countries(isocode,longcode,description) VALUES ('MA','MAR','Morocco');
INSERT INTO countries(isocode,longcode,description) VALUES ('MZ','MOZ','Mozambique');
INSERT INTO countries(isocode,longcode,description) VALUES ('MM','MMR','Myanmar');
INSERT INTO countries(isocode,longcode,description) VALUES ('NA','NAM','Namibia');
INSERT INTO countries(isocode,longcode,description) VALUES ('NR','NRU','Nauru');
INSERT INTO countries(isocode,longcode,description) VALUES ('NP','NPL','Nepal');
INSERT INTO countries(isocode,longcode,description) VALUES ('NL','NLD','Netherlands');
INSERT INTO countries(isocode,longcode,description) VALUES ('AN','ANT','Netherlands Antilles');
INSERT INTO countries(isocode,longcode,description) VALUES ('NC','NCL','New Caledonia');
INSERT INTO countries(isocode,longcode,description) VALUES ('NZ','NZL','New Zealand');
INSERT INTO countries(isocode,longcode,description) VALUES ('NI','NIC','Nicaragua');
INSERT INTO countries(isocode,longcode,description) VALUES ('NE','NER','Niger');
INSERT INTO countries(isocode,longcode,description) VALUES ('NG','NGA','Nigeria');
INSERT INTO countries(isocode,longcode,description) VALUES ('NU','NIU','Niue ');
INSERT INTO countries(isocode,longcode,description) VALUES ('NF','NFK','Norfolk Island');
INSERT INTO countries(isocode,longcode,description) VALUES ('MP','MNP','Northern Mariana Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('NO','NOR','Norway');
INSERT INTO countries(isocode,longcode,description) VALUES ('OM','OMN','Oman');
INSERT INTO countries(isocode,longcode,description) VALUES ('PK','PAK','Pakistan');
INSERT INTO countries(isocode,longcode,description) VALUES ('PW','PLW','Palau');
INSERT INTO countries(isocode,longcode,description) VALUES ('PS','PSE','Palestinian Territory, Occupied');
INSERT INTO countries(isocode,longcode,description) VALUES ('PA','PAN','Panama');
INSERT INTO countries(isocode,longcode,description) VALUES ('PG','PNG','Papua New Guinea');
INSERT INTO countries(isocode,longcode,description) VALUES ('PY','PRY','Paraguay');
INSERT INTO countries(isocode,longcode,description) VALUES ('PE','PER','Peru');
INSERT INTO countries(isocode,longcode,description) VALUES ('PH','PHL','Philippines');
INSERT INTO countries(isocode,longcode,description) VALUES ('PN','PCN','Pitcairn');
INSERT INTO countries(isocode,longcode,description) VALUES ('PL','POL','Poland');
INSERT INTO countries(isocode,longcode,description) VALUES ('PT','PRT','Portugal');
INSERT INTO countries(isocode,longcode,description) VALUES ('PR','PRI','Puerto Rico');
INSERT INTO countries(isocode,longcode,description) VALUES ('QA','QAT','Qatar');
INSERT INTO countries(isocode,longcode,description) VALUES ('RE','REU','Réunion');
INSERT INTO countries(isocode,longcode,description) VALUES ('RO','ROU','Romania');
INSERT INTO countries(isocode,longcode,description) VALUES ('RU','RUS','Russian Federation');
INSERT INTO countries(isocode,longcode,description) VALUES ('RW','RWA','Rwanda');
INSERT INTO countries(isocode,longcode,description) VALUES ('BL','BLM','Saint-Barthélemy');
INSERT INTO countries(isocode,longcode,description) VALUES ('SH','SHN','Saint Helena');
INSERT INTO countries(isocode,longcode,description) VALUES ('KN','KNA','Saint Kitts and Nevis');
INSERT INTO countries(isocode,longcode,description) VALUES ('LC','LCA','Saint Lucia');
INSERT INTO countries(isocode,longcode,description) VALUES ('MF','MAF','Saint-Martin (French part)');
INSERT INTO countries(isocode,longcode,description) VALUES ('PM','SPM','Saint Pierre and Miquelon ');
INSERT INTO countries(isocode,longcode,description) VALUES ('VC','VCT','Saint Vincent and Grenadines');
INSERT INTO countries(isocode,longcode,description) VALUES ('WS','WSM','Samoa');
INSERT INTO countries(isocode,longcode,description) VALUES ('SM','SMR','San Marino');
INSERT INTO countries(isocode,longcode,description) VALUES ('ST','STP','Sao Tome and Principe');
INSERT INTO countries(isocode,longcode,description) VALUES ('SA','SAU','Saudi Arabia');
INSERT INTO countries(isocode,longcode,description) VALUES ('SN','SEN','Senegal');
INSERT INTO countries(isocode,longcode,description) VALUES ('RS','SRB','Serbia');
INSERT INTO countries(isocode,longcode,description) VALUES ('SC','SYC','Seychelles');
INSERT INTO countries(isocode,longcode,description) VALUES ('SL','SLE','Sierra Leone');
INSERT INTO countries(isocode,longcode,description) VALUES ('SG','SGP','Singapore');
INSERT INTO countries(isocode,longcode,description) VALUES ('SK','SVK','Slovakia');
INSERT INTO countries(isocode,longcode,description) VALUES ('SI','SVN','Slovenia');
INSERT INTO countries(isocode,longcode,description) VALUES ('SB','SLB','Solomon Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('SO','SOM','Somalia');
INSERT INTO countries(isocode,longcode,description) VALUES ('ZA','ZAF','South Africa');
INSERT INTO countries(isocode,longcode,description) VALUES ('GS','SGS','South Georgia and the South Sandwich Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('SS','SSD','South Sudan');
INSERT INTO countries(isocode,longcode,description) VALUES ('ES','ESP','Spain');
INSERT INTO countries(isocode,longcode,description) VALUES ('LK','LKA','Sri Lanka');
INSERT INTO countries(isocode,longcode,description) VALUES ('SD','SDN','Sudan');
INSERT INTO countries(isocode,longcode,description) VALUES ('SR','SUR','Suriname *');
INSERT INTO countries(isocode,longcode,description) VALUES ('SJ','SJM','Svalbard and Jan Mayen Islands ');
INSERT INTO countries(isocode,longcode,description) VALUES ('SZ','SWZ','Swaziland');
INSERT INTO countries(isocode,longcode,description) VALUES ('SE','SWE','Sweden');
INSERT INTO countries(isocode,longcode,description) VALUES ('CH','CHE','Switzerland');
INSERT INTO countries(isocode,longcode,description) VALUES ('SY','SYR','Syrian Arab Republic (Syria)');
INSERT INTO countries(isocode,longcode,description) VALUES ('TW','TWN','Taiwan, Republic of China');
INSERT INTO countries(isocode,longcode,description) VALUES ('TJ','TJK','Tajikistan');
INSERT INTO countries(isocode,longcode,description) VALUES ('TZ','TZA','Tanzania *, United Republic of');
INSERT INTO countries(isocode,longcode,description) VALUES ('TH','THA','Thailand');
INSERT INTO countries(isocode,longcode,description) VALUES ('TL','TLS','Timor-Leste');
INSERT INTO countries(isocode,longcode,description) VALUES ('TG','TGO','Togo');
INSERT INTO countries(isocode,longcode,description) VALUES ('TK','TKL','Tokelau ');
INSERT INTO countries(isocode,longcode,description) VALUES ('TO','TON','Tonga');
INSERT INTO countries(isocode,longcode,description) VALUES ('TT','TTO','Trinidad and Tobago');
INSERT INTO countries(isocode,longcode,description) VALUES ('TN','TUN','Tunisia');
INSERT INTO countries(isocode,longcode,description) VALUES ('TR','TUR','Turkey');
INSERT INTO countries(isocode,longcode,description) VALUES ('TM','TKM','Turkmenistan');
INSERT INTO countries(isocode,longcode,description) VALUES ('TC','TCA','Turks and Caicos Islands ');
INSERT INTO countries(isocode,longcode,description) VALUES ('TV','TUV','Tuvalu');
INSERT INTO countries(isocode,longcode,description) VALUES ('UG','UGA','Uganda');
INSERT INTO countries(isocode,longcode,description) VALUES ('UA','UKR','Ukraine');
INSERT INTO countries(isocode,longcode,description) VALUES ('AE','ARE','United Arab Emirates');
INSERT INTO countries(isocode,longcode,description) VALUES ('GB','GBR','United Kingdom');
INSERT INTO countries(isocode,longcode,description) VALUES ('US','USA','United States of America');
INSERT INTO countries(isocode,longcode,description) VALUES ('UM','UMI','United States Minor Outlying Islands');
INSERT INTO countries(isocode,longcode,description) VALUES ('UY','URY','Uruguay');
INSERT INTO countries(isocode,longcode,description) VALUES ('UZ','UZB','Uzbekistan');
INSERT INTO countries(isocode,longcode,description) VALUES ('VU','VUT','Vanuatu');
INSERT INTO countries(isocode,longcode,description) VALUES ('VE','VEN','Venezuela (Bolivarian Republic of)');
INSERT INTO countries(isocode,longcode,description) VALUES ('VN','VNM','Viet Nam');
INSERT INTO countries(isocode,longcode,description) VALUES ('VI','VIR','Virgin Islands, US');
INSERT INTO countries(isocode,longcode,description) VALUES ('WF','WLF','Wallis and Futuna Islands ');
INSERT INTO countries(isocode,longcode,description) VALUES ('EH','ESH','Western Sahara');
INSERT INTO countries(isocode,longcode,description) VALUES ('YE','YEM','Yemen');
INSERT INTO countries(isocode,longcode,description) VALUES ('ZM','ZMB','Zambia');
INSERT INTO countries(isocode,longcode,description) VALUES ('ZW','ZWE','Zimbabwe');